config/routes.rb
EnglishReader::Application.routes.draw do
  get "trans/main"

  get "trans/show"

  resources :qa_items

  resources :dummies

  resources :qas

  get "get_words/main"

  get "get_words/show"

  root :to => "texts#index"

  resources :texts

  resources :word_sets

end

app/models/word_set.rb
class WordSet < ActiveRecord::Base
  # accessible
  attr_accessible :en, :jp, :text_id
  
  # Relation
  belongs_to :text
end

app/controllers/word_sets_controller.rb
class WordSetsController < ApplicationController
  # GET /word_sets
  # GET /word_sets.json
  def index
    @word_sets = WordSet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @word_sets }
    end
  end

  # GET /word_sets/1
  # GET /word_sets/1.json
  def show
    @word_set = WordSet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word_set }
    end
  end

  # GET /word_sets/new
  # GET /word_sets/new.json
  def new
    # @word_set = WordSet.new
    if params['text_id'] != nil
      # @word_set = WordSet.new("", "", "", params['text_id'])
      # @word_set = WordSet.new(params['text_id'])
      @word_set = WordSet.new
      @word_set.text_id = params['text_id'].to_i
    else
      @word_set = WordSet.new
    end


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word_set }
    end
  end

  # GET /word_sets/1/edit
  def edit
    @word_set = WordSet.find(params[:id])
  end

  # POST /word_sets
  # POST /word_sets.json
  def create
    @word_set = WordSet.new(params[:word_set])

    respond_to do |format|
      if @word_set.save
        format.html { redirect_to @word_set, notice: 'Word set was successfully created.' }
        format.json { render json: @word_set, status: :created, location: @word_set }
      else
        format.html { render action: "new" }
        format.json { render json: @word_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /word_sets/1
  # PUT /word_sets/1.json
  def update
    @word_set = WordSet.find(params[:id])

    respond_to do |format|
      if @word_set.update_attributes(params[:word_set])
        format.html { redirect_to @word_set, notice: 'Word set was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /word_sets/1
  # DELETE /word_sets/1.json
  def destroy
    @word_set = WordSet.find(params[:id])
    @word_set.destroy

    respond_to do |format|
      format.html { redirect_to word_sets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/word_sets_helper.rb
module WordSetsHelper
end

app/views/word_sets/_form.html.erb
<%= form_for(@word_set) do |f| %>
  <% if @word_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word_set.errors.count, "error") %> prohibited this word_set from being saved:</h2>

      <ul>
      <% @word_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text_id %><br />
    <%= f.number_field :text_id %>
  </div>
  <div class="field">
    English<br />
    <%= f.text_field :en %>
  </div>
  <div class="field">
    Japanese<br />
    <%= f.text_field :jp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/word_sets/edit.html.erb
<h1>Editing word_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @word_set %> |
<%= link_to 'Back', word_sets_path %>

app/views/word_sets/index.html.erb
<h1>Listing word_sets</h1>

<table>
	<tr><%= link_to 'New Word set', new_word_set_path %></tr>
	<tr>
		<th>ID</th>
		<th>English</th>
		<th>Japanese</th>
		<th>Text Id</th>
	</tr>

<% @word_sets.each do |word_set| %>
  <tr>
  	<td class="id"><%= word_set.id %></td>
    <td class="col_english"><%= link_to word_set.en, word_set %></td>
    <td><%= word_set.jp %></td>
    <td class="id"><%= word_set.text_id %></td>
    
  </tr>
<% end %>
</table>

<br />

app/views/word_sets/new.html.erb
<h1>New word_set</h1>

<%= render 'form' %>

<%= link_to 'Back', word_sets_path %>

app/views/word_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>En:</b>
  <%= @word_set.en %>
</p>

<p>
  <b>Jp:</b>
  <%= @word_set.jp %>
</p>

<p>
  <b>Text:</b>
  <%= @word_set.text_id %>
</p>


<%= link_to 'Edit', edit_word_set_path(@word_set) %> |
<td><%= link_to 'Destroy', @word_set, confirm: 'Are you sure?', method: :delete %></td> |

<%= link_to 'Back', word_sets_path %>