config/routes.rb
EnglishReader::Application.routes.draw do
  get "trans/main"

  get "trans/show"

  resources :qa_items

  resources :dummies

  resources :qas

  get "get_words/main"

  get "get_words/show"

  root :to => "texts#index"

  resources :texts

  resources :word_sets

end

app/models/qa.rb
class Qa < ActiveRecord::Base
end

app/controllers/qas_controller.rb
class QasController < ApplicationController
  # GET /qas
  # GET /qas.json
  def index
    @qas = Qa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qas }
    end
  end

  # GET /qas/1
  # GET /qas/1.json
  def show
    @qa = Qa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qa }
    end
  end

  # GET /qas/new
  # GET /qas/new.json
  def new
    @qa = Qa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qa }
    end
  end

  # GET /qas/1/edit
  def edit
    @qa = Qa.find(params[:id])
  end

  # POST /qas
  # POST /qas.json
  def create
    @qa = Qa.new(params[:qa])

    respond_to do |format|
      if @qa.save
        format.html { redirect_to @qa, notice: 'Qa was successfully created.' }
        format.json { render json: @qa, status: :created, location: @qa }
      else
        format.html { render action: "new" }
        format.json { render json: @qa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qas/1
  # PUT /qas/1.json
  def update
    @qa = Qa.find(params[:id])

    respond_to do |format|
      if @qa.update_attributes(params[:qa])
        format.html { redirect_to @qa, notice: 'Qa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qas/1
  # DELETE /qas/1.json
  def destroy
    @qa = Qa.find(params[:id])
    @qa.destroy

    respond_to do |format|
      format.html { redirect_to qas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/q_as_helper.rb
module QAsHelper
end

app/views/qas/_form.html.erb
<%= form_for(@qa) do |f| %>
  <% if @qa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qa.errors.count, "error") %> prohibited this qa from being saved:</h2>

      <ul>
      <% @qa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qas/edit.html.erb
<h1>Editing qa</h1>

<%= render 'form' %>

<%= link_to 'Show', @qa %> |
<%= link_to 'Back', qas_path %>

app/views/qas/index.html.erb
<h1>Listing qas</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Genre</th>
    <th>Link</th>
  </tr>

<% @qas.each do |qa| %>
  <tr>
    <td><%= link_to qa.title, qa %></td>
    <td><%= qa.content %></td>
    <td><%= qa.genre %></td>
    <td><%= qa.link %></td>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Qa', new_qa_path %>

app/views/qas/new.html.erb
<h1>New qa</h1>

<%= render 'form' %>

<%= link_to 'Back', qas_path %>

app/views/qas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @qa.title %>
</p>

<p>
  <b>Link:</b>
  <%= @qa.link %>
</p>

<p>
  <b>Content:</b>
  <%= @qa.content %>
</p>

<p>
  <b>Genre:</b>
  <%= @qa.genre %>
</p>


<%= link_to 'Edit', edit_qa_path(@qa) %> |
<%= link_to 'Destroy', @qa, confirm: 'Are you sure?', method: :delete %> | 
<%= link_to 'Back', qas_path %>