config/routes.rb
EnglishReader::Application.routes.draw do
  get "trans/main"

  get "trans/show"

  resources :qa_items

  resources :dummies

  resources :qas

  get "get_words/main"

  get "get_words/show"

  root :to => "texts#index"

  resources :texts

  resources :word_sets

end

app/models/qa_item.rb
class QaItem < ActiveRecord::Base
end

app/controllers/qa_items_controller.rb
class QaItemsController < ApplicationController
  # GET /qa_items
  # GET /qa_items.json
  def index
    @qa_items = QaItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qa_items }
    end
  end

  # GET /qa_items/1
  # GET /qa_items/1.json
  def show
    @qa_item = QaItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qa_item }
    end
  end

  # GET /qa_items/new
  # GET /qa_items/new.json
  def new
    @qa_item = QaItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qa_item }
    end
  end

  # GET /qa_items/1/edit
  def edit
    @qa_item = QaItem.find(params[:id])
  end

  # POST /qa_items
  # POST /qa_items.json
  def create
    @qa_item = QaItem.new(params[:qa_item])

    respond_to do |format|
      if @qa_item.save
        format.html { redirect_to @qa_item, notice: 'Qa item was successfully created.' }
        format.json { render json: @qa_item, status: :created, location: @qa_item }
      else
        format.html { render action: "new" }
        format.json { render json: @qa_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qa_items/1
  # PUT /qa_items/1.json
  def update
    @qa_item = QaItem.find(params[:id])

    respond_to do |format|
      if @qa_item.update_attributes(params[:qa_item])
        format.html { redirect_to @qa_item, notice: 'Qa item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qa_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qa_items/1
  # DELETE /qa_items/1.json
  def destroy
    @qa_item = QaItem.find(params[:id])
    @qa_item.destroy

    respond_to do |format|
      format.html { redirect_to qa_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/qa_items_helper.rb
module QaItemsHelper
end

app/views/qa_items/_form.html.erb
<%= form_for(@qa_item) do |f| %>
  <% if @qa_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qa_item.errors.count, "error") %> prohibited this qa_item from being saved:</h2>

      <ul>
      <% @qa_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qa_items/edit.html.erb
<h1>Editing qa_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @qa_item %> |
<%= link_to 'Back', qa_items_path %>

app/views/qa_items/index.html.erb
<h1>Listing qa_items</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Link</th>
    <th>Content</th>
    <th>Genre</th>
    
  </tr>

<% @qa_items.each do |qa_item| %>
  <tr>
    <td><%= link_to qa_item.title, qa_item %></td>
    <td class="id"><%= link_to 'Go', qa_item.link, :target => "_blank" %></td>
    <td><%= qa_item.content %></td>
    <td><%= qa_item.genre %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Qa item', new_qa_item_path %>

app/views/qa_items/new.html.erb
<h1>New qa_item</h1>

<%= render 'form' %>

<%= link_to 'Back', qa_items_path %>

app/views/qa_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @qa_item.title %>
</p>

<p>
  <b>Link:</b>
  <%= @qa_item.link %>
</p>

<p>
  <b>Content:</b>
  <%= @qa_item.content %>
</p>

<p>
  <b>Genre:</b>
  <%= @qa_item.genre %>
</p>


<%= link_to 'Edit', edit_qa_item_path(@qa_item) %> |
<td><%= link_to 'Destroy', @qa_item, confirm: 'Are you sure?', method: :delete %></td> | 
<%= link_to 'Back', qa_items_path %>