config/routes.rb
EnglishReader::Application.routes.draw do
  get "trans/main"

  get "trans/show"

  resources :qa_items

  resources :dummies

  resources :qas

  get "get_words/main"

  get "get_words/show"

  root :to => "texts#index"

  resources :texts

  resources :word_sets

end

app/models/text.rb
class Text < ActiveRecord::Base
  attr_accessible :text, :url, :title
  
  # Relation
  has_many :word_sets
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @texts }
    end
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
    @text = Text.find(params[:id])
    
    # Get text from Text
    text_text = @text.text
    
    # Get the word sets
    word_sets_special = WordSet.where('text_id = ?', @text.id)
    
    # Initialize modified text
    @modified_text = text_text
    
    # Build text
    word_sets_special.each do |word_set|
      @modified_text = @modified_text.sub( \
                  word_set.en, \
                  "<span class='translate' id='word_" + word_set.id.to_s + "'>" + \
                  word_set.en + "</span>")
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text }
    end
  end

  # GET /texts/new
  # GET /texts/new.json
  def new
    @text = Text.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @text }
    end
  end

  # GET /texts/1/edit
  def edit
    @text = Text.find(params[:id])
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(params[:text])

    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: 'Text was successfully created.' }
        format.json { render json: @text, status: :created, location: @text }
      else
        format.html { render action: "new" }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /texts/1
  # PUT /texts/1.json
  def update
    @text = Text.find(params[:id])

    respond_to do |format|
      if @text.update_attributes(params[:text])
        format.html { redirect_to @text, notice: 'Text was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text = Text.find(params[:id])
    @text.destroy
    
    # Related word sets
    @word_sets_special = WordSet.where("text_id = ?", params[:id])
    
    @word_sets_special.each do |word_set|
      # @text.update_attributes(params[:text])
      # word_set.text_id = 0
      word_set.update_attribute(:text_id, 0)
    end

    respond_to do |format|
      format.html { redirect_to texts_url }
      format.json { head :no_content }
    end
  end

  def get_translation
    print "get_translation"
  end
  

end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/texts/_form.html.erb
<%= form_for(@text) do |f| %>
  <% if @text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% @text.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/texts/edit.html.erb
<h1>Editing text</h1>

<%= render 'form' %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<h1>Listing texts</h1>

<table>
	<tr><%= link_to 'New Text', new_text_path %></tr>
  <tr>
  	<th>Id</th>
    <th>Title</th>
    <th>Text</th>
    <th>URL</th>
    <th></th>
    <th></th>
  </tr>

<% @texts.each do |text| %>
  <tr>
  	<td class="id"><%= text.id %></td>
  	
    <% if text.title.length == 0 %>
  		<td class="col_title"><%= link_to "NO TITLE", text.url, {:target => "_blank"} %></td>
	<% else %>
		<td class="col_title"><%= link_to text.title, text %></td>
	<% end %>
	
    <% if text.text.length == 0 %>
  		<td><%= "NO TEXT" %></td>
	<% else %>
		<td class="col_text"><%= text.text[0..50] + "..." %></td>
	<% end %>
    
    <td class="id"><%= link_to "Go", text.url, {:target => "_blank"} %></td>
    
    <td><%= link_to 'Add new words', 
    				:controller => "word_sets", :action => "new", 
    				:text_id => text.id %></td>
    <td><%= link_to 'Get word sets', 
    				:controller => "get_words", :action => "show", 
    				:text_id => text.id %></td>
  </tr>
<% end %>
</table>

app/views/texts/new.html.erb
<h1>New text</h1>

<%= render 'form' %>

<%= link_to 'Back', texts_path %>

app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b><br/>
  <%= @text.title %>
</p>

<p>
  <b>Text:</b><br/>
  <%#= @text.text %>
  <%= raw @modified_text %>
  
</p>

<p>
  <b>Url:</b><br/>
  <%= link_to @text.url, @text.url %>
</p>


<%= link_to 'Edit', edit_text_path(@text) %> |
<td><%= link_to 'Destroy', @text, confirm: 'Are you sure?', method: :delete %></td> |
<%= link_to 'Back', texts_path %>
<br/>
<td><%= link_to 'Add new words', 
    				:controller => "word_sets", :action => "new", 
    				:text_id => @text.id %></td>
<br/>
<br/>

<hr/>
<div id="translation_area"></div>